# Generated by Django 5.2.1 on 2025-05-30 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('icone', models.ImageField(upload_to='imagens/icones')),
                ('descricao', models.CharField(max_length=255)),
                ('data_inserido', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/%Y/%m')),
                ('data_adicionado', models.DateField(default=django.utils.timezone.now)),
                ('prioridade', models.CharField(max_length=15)),
                ('por_que', models.TextField()),
                ('comprado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=100)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('link', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.item')),
            ],
        ),
    ]
