# Generated by Django 5.2.1 on 2025-06-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MÉDIA', 'Média'), ('Alta', 'Alta')], default='MÉDIA', max_length=15),
        ),
    ]
